#!/usr/bin/env bash
# 3-redirection

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index
config='\
	location = \/redirect_me {\
                return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\
        }'
sudo sed -i "/server_name _;/a $config" /etc/nginx/sites-available/default
sudo service nginx restart
