#!/usr/bin/env bash
# 4-not_found_page_404

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index
echo "Ceci n'est pas une page" > /var/www/html/404.html
config='\
	error_page 404 /404.html;'
sudo sed -i "/server_name _;/a $config" /etc/nginx/sites-available/default
sudo service nginx restart
