#!/usr/bin/env bash
# shellcheck disable=SC2154
# 0-custom_http_response_header

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.origin
server_config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;

	index index.html index.htm index.nginx-debian.html;

	server_name _;

	add_header X-Served-By \$hostname;

	error_page 404 /404.html;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files \$uri \$uri/ =404;
	}

	location = /redirect_me {
                return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;
        }
}"
echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
sudo service nginx restart
