#!/usr/bin/env bash
# A script that pings an IP address passed as an argument.

file_name=$(basename "${BASH_SOURCE[@]}")

if [ $# -eq 0 ]
then
	echo "Usage: ${file_name} {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
