#!/usr/bin/env bash
#1-run_nginx_as_nginx
chmod 644 /etc/nginx/nginx.conf
sed -i 's/user root;/user nginx;/g' /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
